### ISSUE TITLE
AsciicastWorker fails with EOF Error

### ISSUE THREAD

**Issue by th0m** [asciinema/asciinema.org#164]
Hi sickill,

First of all, thanks a lot for the awesome work and for sharing everything on GitHub.
I successfully installed everything in an arch Docker container yesterday night but still got some issues when uploading screencast to my asciinema.org instance.

When I upload a new screencast I first get this error from sidkiq.

```
2014-06-17T13:23:52Z 782 TID-3qtes AsciicastWorker JID-e3b956d4b7c712ea7b858840 INFO: start
2014-06-17T13:23:52Z 782 TID-3qtes AsciicastWorker JID-e3b956d4b7c712ea7b858840 INFO: fail: 0.114 sec
2014-06-17T13:23:52Z 782 TID-3qtes WARN: {"retry"=>true, "queue"=>"default", "class"=>"AsciicastWorker", "args"=>[5], "jid"=>"e3b956d4b7c712ea7b858840", "enqueued_at"=>1403011346.2807562, "error_message"=>"end of file reached", "error_class"=>"EOFError", "failed_at"=>"2014-06-17T13:22:26Z", "retry_count"=>2, "retried_at"=>2014-06-17 13:23:52 UTC}
2014-06-17T13:23:52Z 782 TID-3qtes WARN: end of file reached
2014-06-17T13:23:52Z 782 TID-3qtes WARN: /root/asciinema.org/app/models/terminal.rb:51:in `readline'
/root/asciinema.org/app/models/terminal.rb:51:in `read_line'
/root/asciinema.org/app/models/terminal.rb:18:in `snapshot'
/root/asciinema.org/app/services/film.rb:13:in `snapshot_at'
/root/asciinema.org/app/services/asciicast_snapshot_updater.rb:12:in `block in generate_snapshot'
/root/asciinema.org/app/models/asciicast.rb:64:in `with_terminal'
/root/asciinema.org/app/services/asciicast_snapshot_updater.rb:11:in `generate_snapshot'
/root/asciinema.org/app/services/asciicast_snapshot_updater.rb:4:in `update'
/root/asciinema.org/app/services/asciicast_processor.rb:4:in `process'
/root/asciinema.org/app/workers/asciicast_worker.rb:7:in `perform'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/usr/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.7.1.182/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `block in call'
/usr/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.7.1.182/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:339:in `perform_action_with_newrelic_trace'
/usr/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.7.1.182/lib/new_relic/agent/instrumentation/sidekiq.rb:21:in `call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:86:in `do_defer'
/usr/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:37:in `process'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/usr/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

And when I'm trying to watch the screencast on the website I get this error from the Rails App

```
Started GET "/a/4.json" for 172.17.42.1 at 2014-06-17 13:21:53 +0000
Processing by AsciicastsController#show as JSON
  Parameters: {"id"=>"4"}
  Asciicast Load (1.2ms)  SELECT "asciicasts".* FROM "asciicasts" WHERE "asciicasts"."id" = $1 LIMIT 1  [["id", "4"]]
Completed 406 Not Acceptable in 8ms
  User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 2 LIMIT 1

ActionController::UnknownFormat (ActionController::UnknownFormat):
  app/controllers/asciicasts_controller.rb:19:in `show'


  Rendered /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.5ms)
  Rendered /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/_trace.erb (6.3ms)
  Rendered /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (4.8ms)
  Rendered /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (46.3ms)
```

Database wise, I got everything set up : PostgreSQL, Redis.
Also, the asciicast seems to be correctly uploaded on the server, I found the following files : 

```
[root@58411e718297 asciinema.org]# ls -l public/uploads/asciicast/*/5/
public/uploads/asciicast/stdout/5/:
total 4
-rw-r--r-- 1 root root 230 Jun 17 13:22 stdout

public/uploads/asciicast/stdout_timing/5/:
total 4
-rw-r--r-- 1 root root 107 Jun 17 13:22 stdout.time
```

Do you have any idea where I can look at to get it working ?
Thanks a lot in advance and keep up the good work.

**Comment by oscarmlage** [comment]
Hey @th0m great job!, is there any way to get the Dockerfile + run script? Do you plan to make public the way to build the image?. Thank you in advance.
