### ISSUE TITLE
[db:migrate] error on migration - undefined method `file_changed?'

### ISSUE THREAD

**Issue by XVilka** [asciinema/asciinema.org#195]
```
r2tv@xserver ~/asciinema.org $ bundle exec rake --trace db:migrate RAILS_ENV=development
Digest::Digest is deprecated; use Digest
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20141115172153 AddSecretTokenToAsciicasts: migrating =======================
-- add_column(:asciicasts, :secret_token, :string)
   -> 0.0010s
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `file_changed?' for #<Asciicast:0x000ab427360318>/home/r2tv/.gem/ruby/2.1.0/gems/activemodel-4.1.11/lib/active_model/attribute_methods.rb:435:in 
`method_missing'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/attribute_methods.rb:213:in `method_missing'
/home/r2tv/.gem/ruby/2.1.0/gems/carrierwave-0.8.0/lib/carrierwave/mount.rb:249:in `store_previous_model_for_file'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:161:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:161:in `block in halting'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `block in call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `each'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/r2tv/.gem/ruby/2.1.0/gems/bugsnag-2.2.1/lib/bugsnag/rails/active_record_rescue.rb:14:in `run_callbacks'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/callbacks.rb:310:in `_update_record'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/timestamp.rb:70:in `_update_record'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/persistence.rb:484:in `create_or_update'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/r2tv/.gem/ruby/2.1.0/gems/bugsnag-2.2.1/lib/bugsnag/rails/active_record_rescue.rb:14:in `run_callbacks'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/callbacks.rb:302:in `create_or_update'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/persistence.rb:103:in `save'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/validations.rb:51:in `save'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:208:in `transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:268:in `block in save'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:267:in `save'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/persistence.rb:222:in `update_attribute'
/home/r2tv/asciinema.org/db/migrate/20141115172153_add_secret_token_to_asciicasts.rb:6:in `block in change'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:52:in `block (2 levels) in find_each'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:52:in `each'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:52:in `block in find_each'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:126:in `find_in_batches'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:51:in `find_each'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/querying.rb:9:in `find_each'
/home/r2tv/asciinema.org/db/migrate/20141115172153_add_secret_token_to_asciicasts.rb:5:in `change'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:602:in `exec_migration'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/usr/lib64/ruby/2.1.0/benchmark.rb:279:in `measure'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:585:in `block in migrate'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:584:in `migrate'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:759:in `migrate'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:208:in `transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:959:in `block in migrate'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:955:in `each'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:955:in `migrate'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:814:in `up'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:792:in `migrate'
/home/r2tv/.gem/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/r2tv/.gem/ruby/2.1.0/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
/home/r2tv/.gem/ruby/2.1.0/bin/rake:23:in `load'
/home/r2tv/.gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by sickill** [comment]
@XVilka were you able to proceed or this was a blocker for you?

**Comment by XVilka** [comment]
@sickill this was a blocker for me. Still didn't upgrade.

**Comment by sickill** [comment]
I think the problem is with carrierwave hooks. Try commenting out all the `mount_uploader ...` lines in `app/models/asciicast.rb`, then running `db:migrate`.

**Comment by sickill** [comment]
I'm closing old issues. Please reopen if this is still a problem for you or if you can provide more details.

**Comment by sickill** [comment]
Btw, we have new setup guide: https://github.com/asciinema/asciinema.org/blob/master/docs/INSTALL.md
