### ISSUE TITLE
dockerized problem in the sidekiq-in-container

### ISSUE THREAD

**Issue by zminds** [asciinema/asciinema.org#225]
> It take too long time to show the record on my private asciinema that deploy by docker 

![image](https://cloud.githubusercontent.com/assets/1445705/20094668/4311e17c-a5dd-11e6-8840-b068cce6a064.png)

```
2016-11-07T14:29:48.531Z 1 TID-god2sasj0 AsciicastWorker JID-5327096c4df3f941edb43795 INFO: start
2016-11-07T14:29:48.557Z 1 TID-god2sasj0 AsciicastWorker JID-5327096c4df3f941edb43795 INFO: fail: 0.026 sec
2016-11-07T14:29:48.558Z 1 TID-god2sasj0 WARN: {"retry"=>true, "queue"=>"default", "class"=>"AsciicastWorker", "args"=>[1], "jid"=>"5327096c4df3f941edb43795", "enqueued_at"=>1478528988.5296, "error_message"=>"No such file or directory @ rb_sysopen - /app/uploads/asciicast/file/1/asciicast.json", "error_class"=>"Errno::ENOENT", "failed_at"=>1478528988.5567763, "retry_count"=>0}
2016-11-07T14:29:48.558Z 1 TID-god2sasj0 WARN: No such file or directory @ rb_sysopen - /app/uploads/asciicast/file/1/asciicast.json
2016-11-07T14:29:48.558Z 1 TID-god2sasj0 WARN: /root/.rbenv/versions/2.1.7/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/root/.rbenv/versions/2.1.7/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/root/.rbenv/versions/2.1.7/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/app/app/models/stdout.rb:14:in `each'
/app/app/models/stdout.rb:84:in `each'
/app/app/services/film.rb:28:in `stdout_each_until'
/app/app/services/film.rb:9:in `snapshot_at'
/app/app/services/asciicast_snapshot_updater.rb:13:in `block in generate_snapshot'
/app/app/models/asciicast.rb:123:in `with_terminal'
/app/app/services/asciicast_snapshot_updater.rb:12:in `generate_snapshot'
/app/app/services/asciicast_snapshot_updater.rb:5:in `update'
/app/app/services/asciicast_processor.rb:4:in `process'
/app/app/workers/asciicast_worker.rb:7:in `perform'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:122:in `call'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/retry_jobs.rb:73:in `call'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/logging.rb:22:in `with_context'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:127:in `call'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:51:in `block in process'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:94:in `stats'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:50:in `process'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/root/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
2016-11-07T14:30:44.116Z 1 TID-god2sasj0 AsciicastWorker JID-5327096c4df3f941edb43795 INFO: start
2016-11-07T14:30:44.124Z 1 TID-god2sasj0 AsciicastWorker JID-5327096c4df3f941edb43795 INFO: fail: 0.008 sec
2016-11-07T14:30:44.125Z 1 TID-god2sasj0 WARN: {"retry"=>true, "queue"=>"default", "class"=>"AsciicastWorker", "args"=>[1], "jid"=>"5327096c4df3f941edb43795", "enqueued_at"=>1478528988.5296, "error_message"=>"No such file or directory @ rb_sysopen - /app/uploads/asciicast/file/1/asciicast.json", "error_class"=>"Errno::ENOENT", "failed_at"=>1478528988.55678, "retry_count"=>1, "retried_at"=>1478529044.1242547}
2016-11-07T14:30:44.125Z 1 TID-god2sasj0 WARN: No such file or directory @ rb_sysopen - /app/uploads/asciicast/file/1/asciicast.json
2016-11-07T14:30:44.125Z 1 TID-god2sasj0 WARN: /root/.rbenv/versions/2.1.7/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
```

**Comment by sickill** [comment]
Seems like the app is looking for the file in the wrong directory (`/app/app/models/stdout.rb` vs `/app/uploads/asciicast/file/1/asciicast.json`). Any ideas @foobarto ?

**Comment by foobarto** [comment]
No worries I'll have a look once I'm back home later today.

**Comment by ianmiell** [comment]
I'm getting this too.

**Comment by umutkacar** [comment]
Same issue here.

**Comment by sickill** [comment]
`/app/uploads` needs to be made a volume and be accessible from both web server and sidekiq containers.

**Comment by foobarto** [comment]
Apologies for such a long delay... life happened and then I completely forgot about this. Please find pull request with a fix to the Dockerfile and also an additional docker-compose.yml file that simplifies running it on local machine.

I think a better fix would be making sidekiq not expecting that it is hosted somewhere that it can access same folder as the web server. This limits ways of how asciinema/sidekiq can be scaled out.

**Comment by sickill** [comment]
@foobarto thanks! Great idea to provide docker-compose file 👍 

I agree that it would be better to not share the volume with uploads. In fact, you can use S3 as a storage (by setting `S3_*` env vars) and then you don't need to expose `/app/uploads`. But most people run the whole thing on a single host so it's just convenient to share the volume like you did in docker-compose.

**Comment by ianmiell** [comment]
@foobarto Thank you very much for this.
